### ISSUE TITLE
Not working after summer 2023 update

### ISSUE THREAD

**Issue by higps** [Scags/TF2-Building-Overhaul#6]
I am not able to build any additional sentries or dispensers, but I am able to build 1 additional set of teleporters, regardless of what the cvars are set to (more than 1).

**Comment by Scags** [comment]
Please update your gamedata -> [here](https://raw.githubusercontent.com/Scags/TF2-Building-Overhaul/main/addons/sourcemod/gamedata/tf2.buildingoverhaul.txt)

**Comment by higps** [comment]
> Please update your gamedata -> [here](https://raw.githubusercontent.com/Scags/TF2-Building-Overhaul/main/addons/sourcemod/gamedata/tf2.buildingoverhaul.txt)

The file you linked is identical to the one already on my server. I have the updated gamedata already.

**Comment by Scags** [comment]
Strange, are you sure? I'm able to run this on both Windows and Linux on a fresh server install with no issues.

What OS are you using? There might also be a chance of another plugin causing conflicts, although I'm unsure.
![image](https://github.com/Scags/TF2-Building-Overhaul/assets/28571071/be4f9d80-5aa5-4929-80a5-5346c94016f4)

**Comment by higps** [comment]
I am on linux, There was a rogue plugin that had snuck itself in to a folder. 

It works now

**Comment by Scags** [comment]
Great. Glad you got it fixed.
