### ISSUE TITLE
Segfault after x64 update

### ISSUE THREAD

**Issue by kmak7** [Scags/TF2-Building-Overhaul#8]
Server instantly seg faults and crashes if you try to place any building even if its first one after x64 update.

Server OS: Linux Debian
Source Mod version: 1.12
Dependancy and plugin versions: All latest from github

**Comment by Scags** [comment]
If you're running this on a x64 server then yes it will definitely not work until SourceMod is able to provide 64 bit address arithmetic support. If you're running on a 32 bit server still can you provide a throttle link so I can check it out?

**Comment by kmak7** [comment]
I havent changed launch parameters so I think it's running in 64bit mode if it switched automaticaly. How do I force it to run in 32bit mode?

nvm I see there is srcds_run and srcds_run_64. I'm using lgsm and in its config it says executable="./srcds_run" so looks like its running in 32bit mode

how do I provide throttle link?

**Comment by Scags** [comment]
Ok. Download [this](https://forums.alliedmods.net/showthread.php?t=277703) and set up your steam account with it. Next time your server crashes, you'll be able to sign into [crash.limetech.org](https://crash.limetech.org/) and see a link you can share. I should hopefully be able to handle it from there.

**Comment by kmak7** [comment]
https://crash.limetech.org/u6brjkusq3x3

**Comment by Scags** [comment]
Ok thanks. I'll see if I can get to it some time this week.

**Comment by Scags** [comment]
Ok maybe this is easier than I thought. Can you do me a favor? On your server, go to [tf/addons/sourcemod/gamedata/tf2.buildingoverhaul.txt](https://github.com/Scags/TF2-Building-Overhaul/blob/main/addons/sourcemod/gamedata/tf2.buildingoverhaul.txt#L128) line 128 and change the "38" to "39" and let me know if that works.

**Comment by kmak7** [comment]
Yep this fixed the crashing

**Comment by Scags** [comment]
OK perfect. Closing the issue.
